# This is a modified default config file (compared to the original SUMO2 one).
# It is the one used for the best model.

data:
  directory: 'input'
  file_name: 'subjects.pickle'

  split:
    train: 'train'
    validation: 'val'
    cross_validation: Null
    test: 'test'

  batch_size: 12
  preprocessing: False
  augmentation: False
  augmentation_params:
    scaling_factor_range: 0.5

experiment:
  general:
    float32_matmul_precision: 'highest'

  model:
    n_classes: 2
    activation: 'ReLU'
    depth: 2
    channel_size: 16
    pools: [ 4, 4 ]
    convolution_params:
      kernel_size: 5
      padding: 'same'
      dilation: 2
    moving_avg_size: 42

  train:
    n_epochs: 800
    early_stopping: 300

    trainer:
      devices: 1
      num_sanity_val_steps: 0

    optimizer:
      class_name: 'Adam'
      params:
        lr: 5.0e-3
        betas: [ 0.9, 0.999 ]
        eps: 1.0e-8
        weight_decay: 0.0

    lr_scheduler: Null

    loss:
      class_name: 'GeneralizedDiceLoss'
      params: { }

  validation:
    overlap_threshold_step: 0.05
